const elements = [
  {
    name: 'HYDROGEN',
    modelPath: './models/hydrogen/h.obj',
    texture:"./models/hydrogen/h.mtl",
    thumbnail: 'Elementos/hidrogeno.png',
    status:true,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:0,
    flayer:"",
    information:''
  },
{
    name: 'HIDROGENO',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/lithium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:0,
    flayer:"",
    information:''
  },
{
    name: 'SODIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/sodium.png',
    status:true,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:0,
    flayer:"",
    information:''
  },
{
    name: 'POTASSIUM',
    modelPath: './models/banana/banana.obj',
    texture:"./models/banana/banana.mtl",
    thumbnail: 'Elementos/potasio.png',
    status:true,
    position:1,
    scaleArray: [
      {scaleX: 3},
      {scaleY: 3},
      {scaleZ: 3},
    ],
    periodo:0,
    flayer:"",
    information:''
  },
{
    name: 'rubidium',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/rubidium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:0,
    flayer:"",
    information:''
  },
{
    name: 'CAESIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/caesium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:0,
    flayer:"",
    information:''
  },
{
  name: 'FRANCIUM',
  modelPath: './models/mario/mario.glb',
  texture:"",
  thumbnail: 'Elementos/francium.png',
  status:false,
  position:1,
  scaleArray: [
    {scaleX: 0.3},
    {scaleY: 0.3},
    {scaleZ: 0.3},
  ],
  periodo:0,
  flayer:"",
  information:''
},

 {
    name: 'BERYLLIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/beryllium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:1,
    flayer:"",
    information:''
  },
{
    name: 'MAGNESIUM',
    modelPath: './models/magnesium/sacaPuntas.obj',
    texture:"./models/magnesium/sacaPuntas.mtl",
    thumbnail: 'Elementos/magnesium.png',
    status:true,
    position:1,
    scaleArray: [
      {scaleX: 1},
      {scaleY: 1},
      {scaleZ: 1},
    ],
    periodo:1,
    flayer:"Flayers/magnesium.png",
    information:"It is the eighth most abundant element in the earth's crust, but it does not occur without combining in nature. It is found in large deposits of minerals such as magnesite and dolomite. The sea contains billions of tons of magnesium, and this is the source of a large part of the 850,000 tons produced each year. It is the fourth most abundant element in the human body, present in the muscles and soft tissues (30-40%), bones 60% and extracellular fluids 1%.",
  },
  {
    name: 'CALCIUM',
    modelPath: '/models/Trol.glb',
    texture:"",
    thumbnail: 'Elementos/calcium.png',
    status:true,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:1,
    flayer:"",
    information:''
  },
{
    name: 'STRONTIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/strontium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:1,
    flayer:"",
    information:''
  },
{
    name: 'BARIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/barium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:1,
    flayer:"",
    information:''
  },
{
    name: 'RADIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/radium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:1,
    flayer:"",
    information:''
  },
 {
    name: 'SCANDIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/scandium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:2,
    flayer:"",
    information:''
  },
 {
    name: 'YTTRIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/yttrium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:2,
    flayer:"",
    information:''
  },
 {
    name: 'LANTHANUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/lanthanum.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:2,
    flayer:"",
    information:''
  },
 {
    name: 'ACTINIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/actinium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:2,
    flayer:"",
    information:''
  },
 {
    name: 'TITANIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/titanium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:3,
    flayer:"",
    information:''
  },
 {
    name: 'ZIRCONIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/zirconium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:3,
    flayer:"",
    information:''
  },
 {
    name: 'HAFNIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/hafnium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:3,
    flayer:"",
    information:''
  },
 {
    name: 'RUTHERFORDIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/rutherfordium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:3,
    flayer:"",
    information:''
  },
 {
    name: 'VANADIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/vanadium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:4,
    flayer:"",
    information:''
  },
 {
    name: 'NIOBIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/niobium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:4,
    flayer:"",
    information:''
  },
 {
    name: 'TANTALUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/tantalum.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:4,
    flayer:"",
    information:''
  },
 {
    name: 'DUBNIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/dubnium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:4,
    flayer:"",
    information:''
  },
 {
    name: 'chromium',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/chromium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:5,
    flayer:"",
    information:''
  },
 {
    name: 'MOLIBDENO',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/molibdeno.png',
    status:true,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:5,
    flayer:"",
    information:''
  },
 {
    name: 'TUNGSTEN',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/tungsten.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:5,
    flayer:"",
    information:''
  },
 {
    name: 'seaborgium',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/seaborgium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:5,
    flayer:"",
    information:''
  },
 {
    name: 'MANGANESE',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/manganese.png',
    status:true,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:6,
    flayer:"",
    information:''
  },
 {
    name: 'TECHNETIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/technetium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:6,
    flayer:"",
    information:''
  },
 {
    name: 'RHENIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/rhenium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:6,
    flayer:"",
    information:''
  },
 {
    name: 'bohrium',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/bohrium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:6,
    flayer:"",
    information:''
  },
 {
    name: 'IRON',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/iron.png',
    status:true,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:7,
    flayer:"",
    information:''
  },
 {
    name: 'RUTHENIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/ruthenium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:7,
    flayer:"",
    information:''
  },
 {
    name: 'OSMIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/osmium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:7,
    flayer:"",
    information:''
  },
 {
    name: 'hassium',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/hassium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:7,
    flayer:"",
    information:''
  },
 {
    name: 'COBALT',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/cobalt.png',
    status:true,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:8,
    flayer:"",
    information:''
  },
 {
    name: 'RODIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/rodium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:8,
    flayer:"",
    information:''
  },
 {
    name: 'IRIDIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/iridium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:8,
    flayer:"",
    information:''
  },
 {
    name: 'meitnerio',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/meitnerio.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:8,
    flayer:"",
    information:''
  },
 {
    name: 'NIQUEL',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/niquel.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:9,
    flayer:"",
    information:''
  },
 {
    name: 'PALLADIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/palladium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:9,
    flayer:"",
    information:''
  },
 {
    name: 'platinum',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/platinum.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:9,
    flayer:"",
    information:''
  },
 {
    name: 'darmstadtium',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/darmstadtium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:9,
    flayer:"",
    information:''
  },
 {
    name: 'COPPER',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/copper.png',
    status:true,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:10,
    flayer:"",
    information:''
  },
 {
    name: 'SILVER ',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/silver.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:10,
    flayer:"",
    information:''
  },
 {
    name: 'GOLD',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/gold.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:10,
    flayer:"",
    information:''
  },
 {
    name: 'ROENTGENIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/roentgenium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:10,
    flayer:"",
    information:''
  },
 {
    name: 'ZINC',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/zinc.png',
    status:true,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:11,
    flayer:"",
    information:''
  },
 {
    name: 'CADMIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/cadmium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:11,
    flayer:"",
    information:''
  },
 {
    name: 'MERCURY',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/mercury.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:11,
    flayer:"",
    information:''
  },
 {
    name: 'COPERNICIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/copernicium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:11,
    flayer:"",
    information:''
  },
 {
    name: 'BORON',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/boron.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:12,
    flayer:"",
    information:''
  },
 {
    name: 'ALUMINIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/aluminium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:12,
    flayer:"",
    information:''
  },
 {
    name: 'GALLIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/gallium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:12,
    flayer:"",
    information:''
  },
 {
    name: 'INDIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/indium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:12,
    flayer:"",
    information:''
  },
 {
    name: 'thallium',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/thallium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:12,
    flayer:"",
    information:''
  },
 {
    name: 'nihonium',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/nihonium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:12,
    flayer:"",
    information:''
  },
 {
    name: 'CARBON',
    modelPath: './models/carbon/lapizNuevo.obj',
    texture:'./models/carbon/lapizNuevo.mtl',
    thumbnail: 'Elementos/carbon.png',
    status:true,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:13,
    flayer:"",
    information:''
  },
 {
    name: 'SILICON',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/silicon.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:13,
    flayer:"",
    information:''
  },
 {
    name: 'GERMANIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/germanium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:13,
    flayer:"",
    information:''
  },
 {
    name: 'TIN',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/tin.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:13,
    flayer:"",
    information:''
  },
 {
    name: 'LEAD',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/lead.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:13,
    flayer:"",
    information:''
  },
 {
    name: 'FLEROVIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/flerovium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:13,
    flayer:"",
    information:''
  },
 {
    name: 'NITROGEN',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/nitrogen.png',
    status:true,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:14,
    flayer:"",
    information:''
  },
 {
    name: 'PHOSPHORUS',
    modelPath: './models/phosphorus/fosforo.obj',
    texture:"./models/phosphorus/fosforo.mtl",
    thumbnail: 'Elementos/phosphorus.png',
    status:true,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:14,
    flayer:"",
    information:''
  },
 {
    name: 'ARSENIC',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/arsenic.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:14,
    flayer:"",
    information:''
  },
 {
    name: 'ANTIMONY',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/antimony.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:14,
    flayer:"",
    information:''
  },
 {
    name: 'BISMUTH',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/bismuth.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:14,
    flayer:"",
    information:''
  },
 {
    name: 'MOSCOVIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/moscovium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:14,
    flayer:"",
    information:''
  },
 {
    name: 'OXYGEN',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/oxygen.png',
    status:true,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:15,
    flayer:"",
    information:''
  },
 {
    name: 'SULFUR',
    modelPath: './models/huevo/huevo.obj',
    texture:"./models/huevo/huevo.mtl",
    thumbnail: 'Elementos/sulfur.png',
    status:true,    
    position:1,
    scaleArray: [
      {scaleX: 0.7},
      {scaleY: 0.7},
      {scaleZ: 0.7},
    ],
    periodo:15,
    flayer:"Flayers/sulfur.png",
    information:  "Is naturally found in volcanic areas, also , it is widely found in many minerals, including iron pyrite, galena, gypsum and Epsom salts. It is the seventh most abundant element in the body." +
    "It is involved in numerous biochemical processes in oxidation states. It is absorbed as sulfate from the soil (or seawater) by plants and algae. It is used to make two of the essential amino acids needed to make proteins"

  },
 {
    name: 'SELENIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/selenium.png',
    status:true,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:15,
    flayer:"",
    information:''
  },
 {
    name: 'TELLURIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/tellurium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:15,
    flayer:"",
    information:''
  },
 {
    name: 'POLONIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/polonium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:15,
    flayer:"",
    information:''
  },
 {
    name: 'LIVERMORIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/livermorium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:15,
    flayer:"",
    information:''
  },
 {
    name: 'FLUORINE',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/fluorine.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:16,
    flayer:"",
    information:''
  },
 {
    name: 'CHLORINE',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/chlorine.png',
    status:true,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:16,
    flayer:"",
    information:''
  },
 {
    name: 'BROMINE',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/bromine.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:16,
    flayer:"",
    information:''
  },
 {
    name: 'LODINE',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/lodine.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:16,
    flayer:"",
    information:''
  },
 {
    name: 'ASTATINE',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/astatine.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:16,
    flayer:"",
    information:''
  },
 {
    name: 'TENNESINE',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/tennesine.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:16,
    flayer:"",
    information:''
  },
 {
    name: 'HELIUM',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/helium.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:17,
    flayer:"",
    information:''
  },
 {
    name: 'NEON',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/neon.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:17,
    flayer:"",
    information:''
  },
 {
    name: 'ARGON',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/argon.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:17,
    flayer:"",
    information:''
  },
 {
    name: 'KRYPTON',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/krypton.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:17,
    flayer:"",
    information:''
  },
 {
    name: 'XENON',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/xenon.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:17,
    flayer:"",
    information:''
  },
 {
    name: 'RADON',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/radon.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:17,
    flayer:"",
    information:''
  },
  {
    name: 'ORGANESSON',
    modelPath: './models/mario/mario.glb',
    texture:"",
    thumbnail: 'Elementos/organesson.png',
    status:false,
    position:1,
    scaleArray: [
      {scaleX: 0.3},
      {scaleY: 0.3},
      {scaleZ: 0.3},
    ],
    periodo:17,
    flayer:"",
    information:''
  }
]

export default elements;
  